on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Hello World
        run: echo "Hello, world! ${{ inputs.ENV_NAME }}"

      - name: Print Tag Version
        if: ${{ inputs.ENV_NAME == 'prod' }}
        run: echo "Tag version ${{ github.ref_name }}"
        