name: 'Deploy Develop Branch - Development (AWS INV-DEV)'

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      ENV_NAME: develop