name: 'Deploy Main Branch - Production (AWS INV-PROD)'

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      ENV_NAME: production